name: Backup Git Repository

on: [push]

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_S3_BACKUP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_S3_BACKUP_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Compress and Upload .git directory
        run: |
          set -euo pipefail
          SHA=$(git rev-parse HEAD)
          REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)
          TIMESTAMP=$(date -u "+%Y-%m-%dT%H:%M:%SZ")
          # Compressing .git directory
          tar -C .git -czf "/tmp/${REPO_NAME}-${TIMESTAMP}-${SHA}.tar.gz" .
          # Uploading to S3
          echo aws s3 cp "/tmp/${REPO_NAME}-${TIMESTAMP}-${SHA}.tar.gz" "s3://mediasense-git-repo-office-bkup/${REPO_NAME}/${TIMESTAMP}-${SHA}.tar.gz"
          aws s3 cp "/tmp/${REPO_NAME}-${TIMESTAMP}-${SHA}.tar.gz" "s3://mediasense-git-repo-office-bkup/${REPO_NAME}/${TIMESTAMP}-${SHA}.tar.gz"
          echo "Successful maybe: $?"
          # Backup process completed successfully
